cirruslabs/cirrus-ci-agent

- internal/executor/executor.go
Some users report that they are getting `repository not found` error on occasion and a re-run usually helps. Not clear why with a valid GH auth token this happens for some private repositories. Let's add extra retry and see if it'll help.
> Treat `repository not found` error as retryable

- cmd/agent/main.go
For environments without pre-installed certificates
> Explicitly specify root certificates

- internal/executor/logs.go
> Make sure LogUploader doesn't write to a closed channel

- .cirrus.yml
So it's easier to run integration tests for Cirrus CI
> Build binaries for each PR

- internal/executor/cache.go
Related to https://github.com/cirruslabs/cirrus-ci-docs/issues/681
> Propagate HTTP Cache errors correctly

- internal/executor/logs.go
Fixes https://github.com/cirruslabs/cirrus-ci-docs/issues/693
> Change masked secret string in logs

- internal/http_cache/http_cache.go
Since some build systems like Gradle doesn't like redirects.
> Proxy HTTP GET instead of a redirect

- internal/executor/cache.go
Related to https://github.com/cirruslabs/cirrus-ci-docs/issues/712
> Log long stages of cache population

- .golangci.yml
- internal/executor/cache.go
- internal/executor/utils.go
- internal/hasher/hasher.go
- internal/hasher/hasher_test.go
- internal/targz/targz.go
- internal/targz/targz_test.go
- internal/testutil/fs.go
Resolves #53.
See https://github.com/cirruslabs/cirrus-ci-docs/issues/718.
> Support glob syntax for caching

- internal/executor/executor.go
A slight improvement of #56 for easier diagnostics in the future.
> Don't swallow errors when changing current working directory

- go.mod
- go.sum
- internal/executor/artifacts.go
> Include artifact size in logs

- .cirrus.yml
- internal/executor/cache_test.go
- internal/executor/logs.go
- internal/executor/logs_test.go
- internal/targz/targz_test.go
> Support CIRRUS_LOG_TIMESTAMP behavioral environment variable

- cmd/agent/main.go
- cmd/agent/main_test.go
- pkg/grpchelper/grpchelper.go
- pkg/grpchelper/grpchelper_test.go
For use in https://github.com/cirruslabs/cirrus-cli/pull/173.
> Moved TransportSettings() to a separate package

- .goreleaser.yml
See https://github.com/cirruslabs/cirrus-ci-docs/issues/263#issuecomment-732192654.
> .goreleaser.yml: build for s390x and ppc64le

- .cirrus.yml
> Fixed Apple Silicon release upload

- README.md
Relates to https://github.com/cirruslabs/cirrus-ci-docs/issues/767
> Clarify how the agent is used by the CLI and the Cloud

- .cirrus.yml
- internal/executor/cmd.go
- internal/executor/shell_unix_test.go
Should help with the Zsh behavior on FreeBSD/macOS.
> Run commands in their own sessions

- internal/executor/executor.go
Fixes https://github.com/cirruslabs/cirrus-ci-docs/discussions/822
> Clean up working directory after last command

- internal/executor/executor.go
> Support CIRRUS_CLONE_SUBMODULES

- internal/executor/executor.go
Fixes potential issue and improves debugging experience observed in https://github.com/cirruslabs/cirrus-ci-docs/pull/830#issuecomment-812618218.
> Clone submodules tweaks

- cmd/agent/main.go
- internal/executor/executor.go
Needed for https://github.com/cirruslabs/cirrus-cli/issues/352.
> Remove -clean-working-dir and introduce -pre-created-working-dir flag

- internal/executor/executor.go
See https://github.com/cirruslabs/cirrus-cli/issues/357#issuecomment-814082010.
> Fix -pre-created-working-dir logic

- .cirrus.yml
- internal/executor/executor.go
> Don't exit prematurely on receiving ExitInstruction from the cloud

- go.mod
- go.sum
To pick up details for Flutter reports
> Updated annotations

- cmd/agent/main.go
- internal/executor/executor.go
- internal/signalfilter/signalfilter.go
This fixes a couple of bugs introduced in #136 that were catched by tests.
> A couple of fixes after context.Context refactoring

- go.mod
- go.sum
- internal/executor/utils.go
To be in sync with https://github.com/cirruslabs/cirrus-ci-annotations/pull/33 changes.
> Bump github.com/cirruslabs/cirrus-ci-annotations to 0.3.0

- internal/http_cache/http_cache.go
Since S3 only supports uploads thought PUT
> Use PUT for Uploads

- internal/http_cache/http_cache.go
Print some useful information in case of a failed upload by a direct URL
> Debug output when failed to upload cache

- cmd/agent/main.go
- pkg/grpchelper/grpchelper.go
Needed in https://github.com/cirruslabs/terminal to avoid TLS/gocertifi-related code duplication.
> Introduce TransportSettingsAsDialOption()

- internal/executor/artifacts.go
Before they were closed via defered all together on return
> Close each artifact file after uploading

- internal/executor/terminalwrapper/terminalwrapper.go
To avoid things like https://github.com/cirruslabs/cirrus-ci-docs/issues/912#issuecomment-917781044.
> TerminalWrapper: consider the time we started waiting for the terminal too

- internal/executor/artifacts.go
Resolves https://github.com/cirruslabs/cirrus-ci-docs/issues/913.
Also see https://github.com/cirruslabs/cirrus-cli/pull/462.
> Skip artifacts upload when there are no paths specified

- go.mod
- go.sum
- internal/executor/env.go
- internal/executor/env_test.go
- internal/executor/executor.go
- internal/executor/terminalwrapper/terminalwrapper.go
To improve behavior observed in https://github.com/cirruslabs/cirrus-ci-docs/issues/929#issuecomment-953371833.
> Bump github.com/cirruslabs/terminal and pass OS and task environment to Cirrus Terminal's host

- internal/executor/artifacts.go
Resolves https://github.com/cirruslabs/cirrus-ci-agent/issues/197, alternative approach to https://github.com/cirruslabs/cirrus-ci-agent/pull/198.
> Prevent artifacts upload outside of CIRRUS_WORKING_DIR

- go.mod
- go.sum
See https://github.com/go-git/go-git/pull/111 and https://github.com/go-git/go-git/pull/392.
Resolves #201.
> Fix go-git's "reference delta not found" error

- internal/executor/cache.go
- internal/http_cache/http_cache.go
Add more log statements to the agent log so we have more info for debugging issues
> More logs on cache download failures

- internal/executor/cache.go
- internal/executor/executor.go
- internal/executor/piper/piper.go
- internal/executor/shell.go
- internal/executor/shell_test.go
See https://github.com/cirruslabs/cirrus-ci-agent/issues/218.
> Try to close the piper with timeout before killing the shell commands

- internal/executor/cache.go
The `url.QueryUnescape()` in `http_cache.go` is not needed because that is done automatically by the `http` package.
> Fix handling of cache keys with path separators

- internal/executor/logs.go
> Limit ReadAvailableChunks() result to 1 MiB

- internal/executor/executor.go
And only if it fails like during the recent GH incident, try to fetch merge ref.
We've see bunch of weird but rare transient fetch failures since #247 got deployed.
Fixes https://github.com/cirruslabs/cirrus-ci-docs/issues/1086
> Checkout head for PRs

- internal/executor/vaultunboxer/jwtauth.go
- internal/executor/vaultunboxer/vaultunboxer.go
- feat(vault): add env var for auth path
> Vault improvements

- internal/executor/executor.go
- internal/executor/vaultunboxer/vaultunboxer.go
Caught in GCP's Error Reporting.
> Fix NPE when Vault secret contains no data

- .cirrus.yml
Similarly to https://github.com/cirruslabs/cirrus-cli/pull/597.
> Install Sentry CLI for release

- .cirrus.yml
Instead of the deprecated one.
> Use M1 instances

- internal/executor/artifacts_https.go
See https://github.com/cirruslabs/cirrus-ci-docs/issues/1150.
> Use Certifi's trust database for uploading artifacts over HTTPS

- internal/executor/logs.go
> Typo fix in logs

- internal/executor/vaultunboxer/boxedvalue.go
- internal/executor/vaultunboxer/boxedvalue_test.go
- internal/executor/vaultunboxer/vaultunboxer.go
- internal/executor/vaultunboxer/vaultunboxer_test.go
Resolves https://github.com/cirruslabs/cirrus-ci-agent/issues/292.
> Introduce VAULT_CACHED[...] to explicitly ask for Vault secret caching

- internal/executor/vaultunboxer/boxedvalue.go
- internal/executor/vaultunboxer/boxedvalue_test.go
- internal/executor/vaultunboxer/vaultunboxer.go
- internal/executor/vaultunboxer/vaultunboxer_test.go
See https://github.com/cirruslabs/cirrus-ci-agent/issues/292.
> Vault: use cache by default and introduce VAULT_NOCACHE[...]

- internal/executor/clone.go
- internal/executor/vaultunboxer/vaultunboxer_test.go
Improves https://github.com/cirruslabs/cirrus-ci-docs/issues/791#issuecomment-1615683512.
> Clone instruction: print correct commit hash when using "Merge for PRs"

- .goreleaser.yml
- internal/executor/processdumper/processdumper.go
- internal/executor/processdumper/processdumper_test.go
Resolves https://github.com/cirruslabs/cirrus-ci-docs/issues/1195.
> processdumper: output process executable path if possible

- cmd/processdumper/processdumper.go
- internal/executor/processdumper/processdumper.go
Resolves https://github.com/cirruslabs/cirrus-ci-docs/issues/1195.
> processdumper: output cmdline instead of exe

- go.mod
- go.sum
See https://github.com/cirruslabs/cirrus-ci-docs/issues/1245.
> Bump github.com/cirruslabs/cirrus-ci-annotations to fix Flutter

- internal/executor/executor.go
See https://github.com/cirruslabs/cirrus-cli/issues/661.
> Handle "on_timeout:" execution behavior

- internal/executor/executor.go
To support things like
```yaml
env:
VAR_1: VAULT[some/secret/path data.value]
VAR_2: ${VAR_1}
```
Before this change recursive expansion was done before unboxing.
> Unbox Vault values before merging env

- internal/targz/targz.go
I've had a hard time reproducing the #346, and the code in `executor.Fetch()` and `targz.Unarchive` looks OK at first glance.
One interesting observation is that we use `github.com/klauspost/pgzip` (see https://github.com/cirruslabs/cirrus-ci-agent/pull/52) instead of the default `compress/zlib`, which may negatively impact agent's memory usage.
However, I can't think of a non-hacky way to determine if we'll have enough memory for the compression/decompression step (and then we'll be able to fall-back to the `compress/zlib`).
Another interesting thing I've noticed is that compression and decompression routines try to use the `io.CopyBuffer()`, but degrade to the `io.Copy()` internally due to https://github.com/golang/go/issues/16474, which results in lots of unnecessary allocations.
Here …
> targz: perform less allocations due to weird CopyBuffer logic

- internal/http_cache/ghacache/ghacache.go
The executor seems to be already doing that: https://github.com/cirruslabs/cirrus-ci-agent/blob/72f9fffda72954e45e08f6b0418cc6e28c8fce02/internal/executor/cache.go#L477-L479
> GHA cache: set Content-Length header to avoid getting HTTP 411

- go.mod
- internal/executor/executor.go
Resolves https://github.com/cirruslabs/cirrus-ci-agent/issues/358.
> Call ReportAgentFinished using context.WithoutCancel(ctx)
