cirruslabs/cirrus-ci-agent

- Dockerfile
Right now Cirrus CI when running tasks in Kubernetes uses an init container to download an agent executable from https://api.cirrus-ci.com/assets/linux-amd64-agent. If we'll publish a docker image then we'll be able to cache the binary on Kubernetes nodes directly instead of relying on a CDN.
> Dockerfile for Linux amd64 binary

- Dockerfile
So `mv` and other stuff is available in the image
> Use alpine:latest as base image

- .goreleaser.yml
Not all environments which will download the release artifacts will have a tool to unzip and unarchive the `*.tar.gz` files. Let's just publish the raw binaries. Plus I think GitHub's CDN will zip the files if a client accepts gzip.
> Release uncompressed binaries

- cmd/agent/main.go
- cmd/agent/main_test.go
- go.mod
- go.sum
Let's parse protocol from the endpoint if possible instead of introducing yet another flag. It will be easier to integrate with tooling: you'll need to change one flag instead if one or two.
> Parse API endpoint protocol

- internal/executor/executor.go
- internal/executor/shell.go
- internal/executor/shell_unix_test.go
The latest changes were failing integration tests of Cirrus CI. Reverted and added a test.
Probably need reconsider #16
> Revert "Wait for commandline after killing (#19)"

- internal/network/network.go
- internal/network/network_test.go
No need to wait for the full `waitDuration` if we've already established a connection once.
> Ensure that WaitForLocalPort() will exit as early as possible

- .cirrus.yml
- Dockerfile
Another option is to copy a statically linked rsync binary along with the agent's binary and call rsync from the context of task's container.
> Add rsync to ignore .gitignore files when populating working directory

- internal/http_cache/http_cache.go
This drastically decreases the number of "connection refused" errors caused by races when the HTTP server in a separate goroutine is not started, yet the agent already tries to use it.
Real-world example: https://cirrus-ci.com/task/4627810209759232?command=test#L326
> HTTP cache: don't re-recreate the Listener

- .cirrus.yml
- .golangci.yml
- internal/executor/artifacts.go
- internal/executor/executor.go
- internal/executor/logs.go
- internal/executor/utils.go
- internal/http_cache/http_cache.go
Minimal configuration with `errcheck` disabled for now.
> CI: integrate golangci-lint

- go.mod
- go.sum
See https://github.com/cirruslabs/cirrus-ci-annotations/issues/21.
> Bump cirrus-ci-annotations package to include RuboCop improvements

- go.mod
- go.sum
- internal/targz/targz.go
This is the actual package used in https://github.com/mholt/archiver and positions itself as a drop-in replacement for compress/gzip, but doing things in parallel.
Default concurrency is [`runtime.GOMAXPROCS(0)`](https://golang.org/pkg/runtime/#GOMAXPROCS) and the benchmarks can be found here: https://github.com/klauspost/pgzip#performance
From pgzip's `README.md`:
>You should only use this if you are (de)compressing big amounts of data, say more than 1MB at the time, otherwise you will not see any benefit, and it will likely be faster to use the internal gzip library or this package.
Assuming there will be only a single compression job per task and most caches are larger than 1MB in size, this should be fine to keep this the default.
Resolves #50.
> Switch to pgzip

- internal/executor/executor.go
I wonder if we can also enforce the `CIRRUS_WORKING_DIR` environment variable existence and throw an error if it doesn't set.
> Ensure working directory exists

- internal/executor/cache.go
- internal/hasher/hasher.go
- internal/hasher/hasher_test.go
Tested with this integration test:
```yaml
container:
image: alpine:latest
task:
clone_script: echo 'clone'
cache:
name: glob
folder: "**/cache"
fingerprint_script: echo 'fingerprint!'
reupload_on_changes: true
populate_script:
- mkdir -p cache
- echo 'foo' >> cache/foo.txt
- mkdir -p bar/cache
dirty_script: echo $CIRRUS_TASK_ID >> bar/cache/bar.txt
verify_script: cat cache/foo.txt bar/cache/bar.txt
```
> Populate hasher after unarchiving the cache

- internal/executor/artifacts.go
That's not critical since artifacts have been uploaded but the agent failed to report parsed annotations.
> Don't fail task if failed to report annotations

- cmd/agent/main.go
Also made it always override the file (useful for persistent workers). Plus refactored how logs are reported (via defer).
> Create agent logs in $TMP

- internal/executor/executor.go
When the agent runs a script that [exceeds the timeout](https://cirrus-ci.org/faq/#instance-timed-out) it kills it with `cmd.Process.Kill()`, which [causes `Cmd`'s `ProcessState` field to be `nil`](https://golang.org/pkg/os/exec/#Cmd):
>ProcessState contains information about an exited process, available after a call to Wait or Run.
Ensure that we only retrieve ProcessState of a properly terminated `Cmd`.
> Fix NPE on script timeout

- internal/executor/artifacts.go
- internal/executor/cache.go
- internal/executor/executor.go
- internal/executor/logs.go
This makes sure `CIRRUS_LOG_TIMESTAMP` gets picked up from the task's environment, since task's environment is not propagated to the system's environment available via `os.Getenv` otherwise.
> Use task's environment when initializing LogUploader

- internal/executor/logs.go
- internal/http_cache/http_cache.go
There were reports of http cache being unreliable. I also saw a few occasions when Gradle is reporting timeouts from the cache which looks like we forget to set header and the request goes into a limbo state. In the first commit I made sure status is always set and then also added some logs in the following commits.
> Refactorings to get insights into caching 

- internal/executor/logs.go
- internal/executor/shell.go
Otherwise the caller might go astray when doing a `bytesSent != bytesWritten` comparison.
> Make potential bytes expansion transparent in LogUploader.Write()

- cmd/agent/main.go
In case of a failure the log file will be persisted on the machine for debugging purposes. But unfortunately stop hook invocation will override it.
> Don't override log file in stop hook

- cmd/agent/main.go
By specifying a finit keepalive values (by default it's infinite)
This issue https://github.com/grpc/grpc/issues/15889 made me think about adding these option. Might help with the presumably hangin heartbeats.
> Make gRPC check connection health

- internal/executor/cache.go
- internal/http_cache/http_cache.go
Otherwise it's not working in some environments and users are getting constant cache misses. See https://github.com/cirruslabs/cirrus-ci-docs/issues/727#issuecomment-727255825
> Use http client with certificates for proxying 

- .cirrus.yml
- pkg/grpchelper/grpchelper.go
- pkg/grpchelper/grpchelper_test.go
Needed to support Unix domain sockets on Windows properly.
> TransportSettings: a more finer Unix domain socket schema parsing

- go.mod
- go.sum
To include https://github.com/cirruslabs/cirrus-ci-annotations/pull/26 and https://github.com/cirruslabs/cirrus-ci-annotations/pull/27.
> Bump github.com/cirruslabs/cirrus-ci-annotations to 0.1.0

- cmd/agent/main.go
- internal/executor/executor.go
Since we don't need to clean it in CLI's dirty mode
Noticed it when tried to bump the agent version in CLI
> Separate flag for cleaning working directory

- internal/executor/executor.go
Make sure only `true` will enable this setting and not some `yes` or other arbitrary boolean representation.
> More strict CIRRUS_CLONE_SUBMODULES

- .cirrus.yml
To fix the [failing build](https://cirrus-ci.com/task/5729677265338368) on `master`.
> .cirrus.yml: bump Release task resources

- go.mod
- go.sum
To support Flutter annotations (https://github.com/cirruslabs/cirrus-ci-annotations/pull/29).
> Bump github.com/cirruslabs/cirrus-ci-annotations to 0.2.0

- go.mod
- go.sum
- internal/cirrusenv/cirrusenv.go
- internal/cirrusenv/cirrusenv_test.go
- internal/executor/artifacts.go
- internal/executor/cache.go
- internal/executor/executor.go
- internal/executor/logs.go
I have a little concern in regards to how critically we should treat the errors we get from `cirrusenv` in `performStep`:
* on one side, silently not setting environment variables that the user might expect to be set might result in some nasty security bugs (e.g. leaving the password or token empty)
* on the other side, failing the whole execution due to unability to create `CIRRUS_ENV` file on some platform + agent combinations (especially Windows + Persistent Worker) might be too much
But personally I'd vouch for the fail fast scenario, assuming we have a capacity to delicately roll the changes and see if they work on different configurations.
Resolves #139.
> Ability to share environment variables between task's scripts

- cloudbuild.yaml
Seem for a multi-arch build Cloud Build doesn't recognize `images` field. Instead let's do build and push right away as I found in this tutorial https://github.com/GoogleCloudPlatform/solutions-build-multi-architecture-images-tutorial/blob/593f898ff584ed47c0edc8b15f9f139c8b157b0c/terraform/cloud-build/build-docker-image-trigger.yaml#L28
Also lowered the timeout as `buildx` via QEMU is not that slow.
> Fixed Cloud Build

- internal/executor/cache.go
This fixes the regression introduced in #157: non-glob paths were expanded by [github.com/bmatcuk/doublestar](https://github.com/bmatcuk/doublestar) into an empty array, because the folders these paths are pointing to are non-existent.
> Bring back the cache glob heuristic

- go.mod
- go.sum
- internal/executor/executor.go
To include the default terminal server fix from https://github.com/cirruslabs/terminal/pull/10, otherwise <>:
```
Terminal host failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: address terminal.cirrus-ci.com: missing port in address"
```
Also fixes the missed newlines in log in c2d80e4e1b8a37f7fa11b2d2610e8019cd1a8be1.
> Bump github.com/cirruslabs/terminal to 0.7.0

- internal/executor/cache.go
- internal/http_cache/http_cache.go
Otherwise the Content-Type is set to 'chunked' and S3 presigned URLs do not support "chunked" uploads.
Here is context https://github.com/aws/aws-sdk-go/issues/1414#issuecomment-317573071
> Set Content-Length for cache uploads

- go.mod
- go.sum
- internal/executor/terminalwrapper/terminalwrapper.go
Otherwise the `TerminalWrapper`'s `Wait()` finishes prematurely, before we even had a chance to connect.
> Wait for the terminal session to be established

- internal/executor/terminalwrapper/terminalwrapper.go
https://github.com/cirruslabs/cirrus-ci-agent/commit/7955a101ba780dff775f77a6d8876953d31c9ffa is an obvious one, while the https://github.com/cirruslabs/cirrus-ci-agent/commit/6d9802031bbfcaefa09fd6aa597f04b5e32c7508 makes sure we don't terminate the session too early after receiving the initial connection, which improves UX in the web UI since it's too easy to miss the terminal presence otherwise.
> TerminalWrapper: increase idle time and take into account the last registration time when waiting on activity

- cmd/metrics/metrics.go
- go.mod
- go.sum
- internal/executor/executor.go
- internal/executor/metrics/metrics.go
- internal/executor/metrics/metrics_test.go
- internal/executor/metrics/metrics_unsupported.go
- internal/executor/metrics/source/cgroup/cgroup.go
- internal/executor/metrics/source/cgroup/cpu/cpu.go
- internal/executor/metrics/source/cgroup/cpu/cpu_linux.go
- internal/executor/metrics/source/cgroup/cpu/cpu_unsupported.go
- internal/executor/metrics/source/cgroup/cpu/v1.go
- internal/executor/metrics/source/cgroup/cpu/v2.go
- internal/executor/metrics/source/cgroup/memory/memory.go
- internal/executor/metrics/source/cgroup/memory/memory_linux.go
- internal/executor/metrics/source/cgroup/memory/memory_unsupported.go
- internal/executor/metrics/source/cgroup/memory/v1.go
- internal/executor/metrics/source/cgroup/memory/v2.go
- internal/executor/metrics/source/cgroup/parser/parser.go
- internal/executor/metrics/source/cgroup/parser/parser_test.go
- internal/executor/metrics/source/cgroup/resolver/resolver.go
- internal/executor/metrics/source/cgroup/resolver/resolver_linux.go
- internal/executor/metrics/source/cgroup/resolver/resolver_unsupported.go
- internal/executor/metrics/source/cgroup/subsystem/subsystem.go
- internal/executor/metrics/source/source.go
- internal/executor/metrics/source/system/system.go
This approach completely disregards the notion of container, which gives the following benefits:
* no weird heuristic like checking for `docker` string in `/proc/self/croup` to determine if we're running inside of a container
* more precise resource reporting for Persistent Workers that are being resource-constrained using cgroup
Tested using `go run cmd/metrics/metrics.go` and compared against `htop`/`docker stats` on:
* Debian 10 running cgroup version 1 filesystem
* on the host itself
* inside of a Docker container
* Fedora 33 running cgroup version 2 filesystem
* on the host itself
* inside of a Docker container
Also tested against `kubectl top pods` on:
* GKE
* COS with containerd
* COS with Docker
Resolves #174.
> cgroup-aware metrics collection

- go.mod
- go.sum
To include https://github.com/grpc/grpc-go/pull/4561 and hopefully diagnose https://github.com/cirruslabs/cirrus-ci-docs/issues/913 better.
> Bump google.golang.org/grpc to 1.40.0

- internal/executor/terminalwrapper/terminalwrapper.go
To avoid hangs here, for example:
https://github.com/cirruslabs/cirrus-ci-agent/blob/77a38a36c924f009f5445b0dda6b250a55daf25d/internal/executor/terminalwrapper/terminalwrapper.go#L71
> TerminalWrapper: make operationChan buffered (with 4096 values)

- internal/executor/piper/piper.go
- internal/executor/shell.go
- internal/executor/shell_unix_test.go
- internal/executor/shellcommands.go
- internal/executor/shellcommands_windows.go
Resolves https://github.com/cirruslabs/cirrus-ci-docs/issues/910 by working around https://github.com/golang/go/issues/23019.
This issue was first spotted in https://github.com/cirruslabs/cirrus-ci-agent/issues/23, however, [the PR that fixed it](https://github.com/cirruslabs/cirrus-ci-agent/pull/135) only targets cases where the shell is terminated by a timeout and not cases where the shell has exited cleanly (yet left behind the descendants that referenced it's stderr/stdout file descriptors).
> ShellCommandsAndWait: don't wait for children processes

- go.mod
- go.sum
To include https://github.com/cirruslabs/terminal/pull/19.
> Bump github.com/cirruslabs/terminal to 0.8.2

- go.mod
- go.sum
- internal/executor/artifacts.go
- internal/executor/utils.go
A proper tag will be set in `go.mod` once https://github.com/cirruslabs/cirrus-ci-annotations/pull/36 is merged.
> Bump github.com/cirruslabs/cirrus-ci-annotations to 0.4.1

- go.mod
- go.sum
To include https://github.com/cirruslabs/cirrus-ci-annotations/pull/39.
> Bump github.com/cirruslabs/cirrus-ci-annotations to 0.7.0

- go.mod
- go.sum
- internal/executor/terminalwrapper/terminalwrapper.go
The rationale behind https://github.com/cirruslabs/cirrus-ci-agent/commit/78a57d84ccf1e58302bdfa95598da2c7c20da590 is explained in https://github.com/cirruslabs/terminal/pull/24, and https://github.com/cirruslabs/cirrus-ci-agent/commit/2fda044013c84afbfe828b509fa7b7f1d1c429ad fixes a bug.
Needs https://github.com/cirruslabs/terminal/pull/24 to be merged and released first.
> Wait for the terminal server connection instead of a session + provide task's identification

- internal/executor/terminalwrapper/terminalwrapper.go
This prevents the agent from generating multiple `EXPIRING` lifecycle notifications.
@fkorotkov note that I'm assuming here that we need to fail the "Wait for terminal" step in case `timeout_in` kicks in and `ctx` gets cancelled.
> Terminal wrapper: exit on terminal expiration

- cmd/metrics/metrics.go
- internal/executor/cmd.go
- internal/executor/executor.go
- internal/executor/metrics/metrics.go
- internal/executor/metrics/metrics_test.go
- internal/executor/metrics/metrics_unsupported.go
- internal/executor/metrics/source/cgroup/cpu/cpu_linux.go
- internal/executor/metrics/source/cgroup/cpu/cpu_unsupported.go
- internal/executor/metrics/source/cgroup/cpu/v1.go
- internal/executor/metrics/source/cgroup/cpu/v2.go
- internal/executor/metrics/source/cgroup/memory/memory_linux.go
- internal/executor/metrics/source/cgroup/memory/memory_unsupported.go
- internal/executor/metrics/source/cgroup/memory/v1.go
- internal/executor/metrics/source/cgroup/memory/v2.go
- internal/executor/metrics/source/cgroup/resolver/resolver_unsupported.go
- internal/executor/metrics/source/source.go
- internal/executor/metrics/source/system/system.go
- internal/executor/shell_linux_test.go
- internal/executor/shell_unix_test.go
- internal/executor/shell_windows_test.go
- internal/executor/shellcommands.go
- internal/signalfilter/signalfilter.go
~~As for the `-1.0`, we can convert these values to `null` right in the web UI and get something like this:~~
~~Since we are removing the agent warning generation for metrics, such graph at least gives a glimpse that something is wrong and a "Debugging" modal window can be further investigated for the agent logs.~~
Resolves #196.
> Metrics: fail gracefully

- Dockerfile
To fix the `err hash_sha256_verify checksum for [...] did not verify` error.
> Dockerfile: install goreleaser via Debian packages

- internal/cirrusenv/cirrusenv.go
- internal/cirrusenv/cirrusenv_test.go
- internal/cirrusenv/cirrusenv_windows_test.go
Unfortunately using the `FILE_SHARE_WRITE` flag as suggested in https://github.com/cirruslabs/cirrus-ci-docs/issues/961 doesn't seem to help: [Go already sets this flag](https://github.com/golang/go/blob/16d6a5233a183be7264295c66167d35c689f9372/src/syscall/syscall_windows.go#L332) (I've additionally checked this using Process Monitor on Windows), but the regular `echo` still fails, supposedly because it needs to specify the `FILE_SHARE_WRITE` flag too.
Resolves https://github.com/cirruslabs/cirrus-ci-docs/issues/961.
> Don't hold the CIRRUS_ENV file open

- internal/executor/metrics/metrics.go
- internal/executor/metrics/metrics_test.go
- internal/executor/metrics/metrics_unsupported.go
- internal/executor/shell_subunix_test.go
- internal/executor/shell_unix_test.go
Ran tests on OpenBSD 7.0, should be the same for NetBSD since it goes hand in hand with OpenBSD in build constants.
Resolves #211.
> Disable metrics on {Open,Net}BSD

- internal/http_cache/http_cache.go
- internal/http_cache/rpc_fallback.go
Ability to download/upload cache over RPC was superseded in https://github.com/cirruslabs/cirrus-ci-agent/commit/655ef61a09e2174edee97c4e6a19203f891b47c8, but the CLI's executor still uses this method because it's too cumbersome to passthrough a HTTP server inside of a container from the CLI's side.
This should fix the https://github.com/cirruslabs/cirrus-cli/pull/486 build.
> Implement cache download/upload RPC fallback

- internal/executor/piper/piper.go
- internal/executor/shell.go
After analyzing the https://github.com/cirruslabs/cirrus-ci-agent/pull/214 and fiddling with `os.Pipe` a bit, I've realized that:
1. we currently kill the pipe reading Goroutine prematurely by closing the pipe's read end: https://github.com/cirruslabs/cirrus-ci-agent/blob/d6db03925baaff71707eaec03f9ec80b990eb3f5/internal/executor/piper/piper.go#L40
2. we should instead manage to close all the writing end's copies to get all the data and a proper `EOF`
However, the bigger issue is that we're a bit at loss when it comes to making sure all the writing end's copies are closed, because:
1. we pass the writing end to the arbitrary process
2. it may spawn children which may detach from itself
3. we will then fail to kill that children and it'll keep the writing end open indefinitely, thus …
> Piper: don't close the os.Pipe's read end until we read everything

- internal/executor/executor.go
- internal/executor/piper/piper.go
- internal/executor/shell.go
- internal/executor/shell_unix_test.go
And also support `context.Context` in piper, from https://github.com/cirruslabs/cirrus-ci-agent/pull/216.
> Always kill spawned shell's process group to avoid pipe FD hangs

- internal/http_cache/http_cache.go
- internal/http_cache/rpc_fallback.go
It appeared we forgot to close `Body` of a request which will make the client not to reuse connection in case there are consecutive requests. 
Lame bug which I found while looking if there are some improvements we can do on the agent side for https://github.com/cirruslabs/cirrus-ci-docs/discussions/986
> Don't forget to close body

- internal/http_cache/http_cache.go
By default there is only 2 idle connections per post. In our case most likely there will be only one host to proxy cache from. Let's set `MaxIdleConnsPerHost` accordingly.
> Configure max allowed idle connections

- cmd/agent/main.go
- go.mod
- go.sum
- internal/signalfilter/signalfilter.go
Found a huge agent log with a bunch of entries like:
```
2022/04/02 08:52:57 Captured broken pipe...
2022/04/02 08:52:57 Captured broken pipe...
2022/04/02 08:52:57 Captured broken pipe...
2022/04/02 08:52:57 Captured broken pipe...
2022/04/02 08:52:57 Captured broken pipe...
2022/04/02 08:52:57 Captured broken pipe...
2022/04/02 08:52:57 Captured broken pipe...
2022/04/02 08:52:57 Captured broken pipe...
2022/04/02 08:52:57 Captured broken pipe...
```
Even through it's still unclear what causes this (the agent in question was used to develop https://github.com/cirruslabs/cirrus-cli/pull/493), it makes sense to limit signal reporting just in case.
> Rate-limit signal reporting

- .cirrus.yml
> .cirrus.yml: fix build on FreeBSD

- internal/executor/cache.go
This way the spaces are encoded properly too.
> Use url.PathEscape() instead of url.QueryEscape()

- cmd/agent/main.go
- internal/cirrusenv/cirrusenv_test.go
- internal/executor/cache.go
- internal/executor/executor.go
- internal/executor/logs.go
- internal/executor/utils.go
- internal/hasher/hasher_test.go
- internal/http_cache/http_cache.go
- internal/targz/targz_test.go
- internal/testutil/fs.go
Plus use the same value for Cirrus HTTP cache and the regular cache instructions.
> Bump timeouts for HTTP clients used for caching

- internal/executor/shell.go
- internal/executor/shellcommands.go
- internal/executor/shellcommands_windows.go
Manually tested on GCP machine using a Rust binary calling [`kernel32::GetErrorMode()`](https://docs.rs/kernel32-sys/0.2.2/x86_64-pc-windows-gnu/kernel32/fn.GetErrorMode.html).
See https://github.com/cirruslabs/cirrus-ci-docs/issues/1068.
> Introduce CIRRUS_WINDOWS_ERROR_MODE environment variable

- internal/executor/executor.go
GH's `checkout` action [seems to use this reference for clones](https://github.com/actions/checkout/blob/eb8a193c1dbf4bbb2053320cef52bacc1a485839/__test__/ref-helper.test.ts#L50-L58).
See https://stackoverflow.com/questions/63594658/git-refs-merge-vs-head-in-pull-request
> Use merge reference instead of head

- internal/executor/executor.go
Since the recent change in #247
Otherwise it fails with CIRRUS_CLONE_DEPTH is set to 1 which we don't recommend but people do it.
> Adjust clone depth for PRs

- internal/executor/executor.go
In case merge ref is not available. These edge cases were cauhgt by integration tests in Cirrus CI:
1. Cloning a PR with conflicts.
2. Cloning a closed PR.
Related to #247 and #249
> Fall back to checking out HEAD

- internal/executor/artifacts.go
See https://github.com/cirruslabs/cirrus-ci-docs/discussions/1075.
The actual error is `Read timed out`, so perhaps if the retry mechanism in the agent doesn't work, we may want to tune the keep-alives/timeouts in the gRPC accordingly.
> Artifacts upload: check CloseAndRecv() error

- Dockerfile
Cloud Build machines are too slow for multi-arch builds. Let's increase the timeout from the default 30 minutes.
> Increase timeout

- internal/executor/executor.go
It appeared that PR fetching was not respecting clone depth. Also simplified the logic overall.
> Respect clone depth for PR fetches

- go.mod
- go.sum
To include https://github.com/cirruslabs/cirrus-ci-annotations/pull/42.
> Bump github.com/cirruslabs/cirrus-ci-annotations to 0.9.0

- internal/executor/artifacts.go
- internal/executor/artifacts_https.go
In https://github.com/cirruslabs/cirrus-ci-agent/pull/263, at some point I've done a `git reset --hard` and was using a `master` agent for tests 🤦
This fixes the issues encountered and the integration tests should now pass.
> Support artifacts upload over HTTPS: integration test fixes

- internal/executor/artifacts.go
- internal/executor/utils.go
- internal/targz/targz.go
Also re-instantiate the uploader each try to avoid sending duplicate files.
The artifact-specific integration tests seem to pass just fine.
See https://github.com/cirruslabs/cirrus-ci-docs/issues/1146.
> uploadArtifactsWithRetries: don't overwrite err

- .cirrus.yml
- Dockerfile
- cloudbuild.yaml
GCP's Cloud Build seems having some weird issues when it can't build multiarch images with error like this:
```
runtime: copying /usr/local/go/src/runtime/tls_arm64.h to /tmp/go-buildXXX/tls_GOARCH.h: write /tmp/go-buildXXX/tls_GOARCH.h: copy_file_range: function not implemented
```
Let's also build the image using our Docker Builder and push it to the GitHub registry.
> Push to GitHub Registry

- Dockerfile
- cloudbuild.yaml
No need to attempt building `agent_cgo`
> Build just single binary

- internal/executor/executor.go
It seems we were only checking error message for "timeout" and forgot "timed out".
> Retry clones on "timed out"

- internal/executor/executor.go
This allows for earlier error detection, since it's very unlikely that any command will ever run after `os.Chdir()` fails, because do this for every command:
https://github.com/cirruslabs/cirrus-ci-agent/blob/6093bc7d29d70960aca57f9852a541b2e4c8ff4d/internal/executor/shell.go#L149
See also https://github.com/cirruslabs/cirrus-cli/issues/620#issuecomment-1556779772.
> Make os.Chdir(workingDir) error fatal

- .cirrus.yml
- cmd/agent/main.go
- go.mod
- go.sum
- internal/executor/artifacts_https.go
- internal/executor/clone.go
- internal/executor/vaultunboxer/vaultunboxer.go
- internal/http_cache/http_cache.go
- pkg/grpchelper/grpchelper.go
Specific cases like https://github.com/cirruslabs/cirrus-ci-docs/issues/1150 should still work because even through the `ubuntu:18.04` is EOL, it ships without CA certificates (can be easily verified by running the container and [accessing these paths](https://github.com/golang/go/blob/34c0714bf27bdcc174d67e1243f6e8fd6bb802be/src/crypto/x509/root_linux.go)).
Similarly to https://github.com/cirruslabs/cirrus-cli/pull/628.
> Use x509.SetFallbackRoots and switch away from gocertifi

- internal/executor/clone.go
- internal/executor/clone_test.go
The change in https://github.com/cirruslabs/cirrus-ci-agent/pull/299 was reporting HEAD incorrectly because in cases like `SAME_SHA` we change the HEAD after a call to `repo.Head()`, so we need to call it again.
> Clone instruction: report the actual HEAD

- internal/executor/executor.go
ResourceUtilization field is nil on {Open,Net}BSD.
> Fix NPE when showing details about the received metrics

- cmd/agent/main.go
With this change, we may miss potential panics in the process of log file initialization, but we'll upload log files with panics in them because `defer`'s are stacked in Last-In-First-Out order.
> Save panic to logs before uploading them

- internal/targz/targz.go
- internal/targz/targz_test.go
My normalizing all stored paths to slashes and denormilizing according to OS when unarchiving.
> Make *.tar archiving cross-platform

- internal/executor/shell.go
In order to allow the agent to proxy all outputs of all scripts to the stdout/stderr. This is useful for folks having their own log collectors, for example, Stackdriver integration for GKE.
Made it opt-in since in this scenarios people pay for amount of logs collected, and we don't want to bring surprises to the bills.
> Introduce `CIRRUS_AGENT_EXPOSE_SCRIPTS_OUTPUTS`

- cmd/agent/main.go
- cmd/agent/main_test.go
With this change, the authentication layer can be made more DRY and non-numeric task IDs will be supported.
> Support passing task identification parameters via gRPC metadata

- internal/executor/shell.go
- internal/executor/shell_unix_test.go
This fixes getting a `SIGPIPE` due to piper closure after the child process starts: https://github.com/cirruslabs/cirrus-ci-agent/blob/697ced3a26b6cd8f66a5eea5b0b8ccf9bfd93554/internal/executor/shell.go#L194-L198
No descriptor is inherited by the child process when using `io.MultiWriter`, so let's use it indirectly.
> Don't mess with piper

- internal/executor/vaultunboxer/boxedvalue.go
- internal/executor/vaultunboxer/boxedvalue_test.go
- internal/executor/vaultunboxer/vaultunboxer.go
- internal/executor/vaultunboxer/vaultunboxer_test.go
This PR is adding support to set arguments for fetching credentials.
Some enabled use cases are the following:
- adjust the TTL of AWS credentials
- https://developer.hashicorp.com/vault/api-docs/secret/aws#ttl
- `VAULT[path/aws/sts/role-name access_key ttl=900]`
- select the secret version of a KV entry
- https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2#version
- `VAULT[path/kv/data/entry data.foo version=2]`
To get a cached value, the arguments must be equal.
> feat(vault): add support for arguments

- internal/executor/cmd.go
- internal/executor/shell_unix_test.go
I've created the following script instruction to run on FreeBSD:
```yaml
install_golang_script:
- wget --no-verbose -O - https://go.dev/dl/go1.21.5.freebsd-amd64.tar.gz | tar -C /usr/local -xz
```
And it was marked as succeed, but in reality, it failed because `wget` was not installed:
This seems to be happening because the `pipefail` option is only set on when using Bash:
https://github.com/cirruslabs/cirrus-ci-agent/blob/445a87400c7f080f7bc7a142b76284d47ae61afe/internal/executor/cmd.go#L44-L46
It seems that we can try to enable the `pipefail` option opportunistically by utilizing the `||` (logical OR expression) to avoid failing the whole script if the option is not defined for a given shell.
Also, nowadays most shells seems to support `pipefail`, for example, on OpenBSD, the `/bin/sh` …
> Better pipeline failure detection

- internal/executor/utils.go
I was trying to use `sudo -Hu ubuntu bash` as `CIRRUS_SHELL` so that everything is run under `ubuntu` user rather than `root` but this is currently not possible due to the set permissions:
```
bash: /tmp/scripts52fdfc072182654f163f5f0f9a621d72.sh: Permission denied
Exit status: 126
```
> Allow other users to read the script file

- .cirrus.yml
- go.mod
- go.sum
- internal/environment/expand.go
- internal/executor/cmd.go
- internal/executor/executor.go
- internal/executor/executor_test.go
- internal/executor/metrics/source/cgroup/cpu/cpu_unsupported.go
- internal/executor/metrics/source/cgroup/cpu/v1.go
- internal/executor/metrics/source/cgroup/cpu/v2.go
- internal/executor/metrics/source/cgroup/memory/memory_unsupported.go
- internal/executor/metrics/source/cgroup/memory/v1.go
- internal/executor/metrics/source/cgroup/memory/v2.go
- internal/executor/metrics/source/cgroup/resolver/resolver_unsupported.go
- internal/executor/shell_linux_test.go
- internal/executor/shell_unix_test.go
- internal/executor/shell_windows_test.go
- internal/executor/shellcommands.go
- internal/executor/vaultunboxer/vaultunboxer.go
- internal/executor/vaultunboxer/vaultunboxer_test.go
- internal/signalfilter/signalfilter.go
- internal/testutil/constants.go
- internal/testutil/rpc.go
This achieves the same thing as https://github.com/cirruslabs/cirrus-ci-agent/pull/330, but without delaying the environment variable expansion step that might resolve the variables critical for the Vault client initialization (e.g. `CIRRUS_VAULT_URL`).
Will mark as ready to review once I'll come up with an appropriate test for this.
> Use a separate pre-expanded environment for Vault-unboxing process

- internal/executor/executor.go
Make sure in case of a timeout we run instructions marked as `always` via passing a context with an extended timeout.
> Run `always` instructions on timeout

- .cirrus.yml
- Dockerfile
- go.mod
- go.sum
- internal/http_cache/ghacache/cirruscimock/cirruscimock.go
- internal/http_cache/ghacache/ghacache.go
- internal/http_cache/ghacache/ghacache_test.go
- internal/http_cache/http_cache.go
How to run locally for testing purposes:
1. Generate a JWT token, see `TestGHA`
2. Create a dummy `Dockerfile`, e.g. with `FROM debian:latest` contents
3. `docker buildx build -t whatever --cache-to type=gha,url=http://<your IP reachable from Docker VM>:12321/,token=<token generated in step 1>,scope=image .`
Resolves https://github.com/cirruslabs/cirrus-ci-agent/issues/344.
> HTTP cache: implement GitHub Actions cache endpoints

- internal/http_cache/ghacache/ghacache.go
- internal/http_cache/ghacache/httprange/httprange.go
- internal/http_cache/ghacache/httprange/httprange_test.go
- internal/http_cache/ghacache/uploadable/uploadable.go
- internal/http_cache/ghacache/uploadable/uploadable_test.go
It turns out that the GHA cache protocol writes chunks in parallel using the `Content-Range` headers.
This change adds a support for this and also stores everything in temporary files which are `unlink(2)`'ed at creation.
This PR also correctly returns JSON for all GHA cache response, even for error ones, which [`go-actions-cache` expects](https://github.com/tonistiigi/go-actions-cache/blob/6c9ed76faed5bcb5ffd114720936a166d5f58091/cache.go#L613-L615).
> GHA cache improvements

- internal/http_cache/ghacache/ghacache.go
In the cloud, a different code-path in the agent's HTTP cache kicks that replies with HTTP 200 instead of HTTP 201 for a successful cache upload. Handle that.
See https://cirrus-ci.com/task/6204584780103680?logs=build#L289 for more details.
> ghacache: HTTP 200 is also a good status

- internal/executor/clone.go
Fixes https://github.com/cirruslabs/cirrus-ci-agent/issues/351
> Allow to control fetching tags via `CIRRUS_CLONE_TAGS`

- internal/http_cache/ghacache/cirruscimock/cirruscimock.go
- internal/http_cache/ghacache/ghacache.go
Found this while testing the https://github.com/actions/cache with the following patch:
```js
const httpCacheHost = process.env["CIRRUS_HTTP_CACHE_HOST"];
if (httpCacheHost != null) {
const newActionsCacheURL = `http://${httpCacheHost}/`;
console.log(`Re-defining ACTIONS_CACHE_URL to ${newActionsCacheURL}`);
process.env["ACTIONS_CACHE_URL"] = newActionsCacheURL;
}
```
> GHA cache: do not generate cache IDs larger than JavaScript can support
